=== dam4256/ups-carpooling/Carpooling-Spring-WS/src/main/resources/Localisation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
        attributeFormDefault="unqualified"
        targetNamespace="http://ups/fr/carpooling/schemas">
    <xs:element name="LocalisationRequest" type="cp:LocalisationRequestType" xmlns:cp="http://ups/fr/carpooling/schemas"/>
    <xs:element name="LocalisationResponse" type="cp:LocalisationResponseType" xmlns:cp="http://ups/fr/carpooling/schemas"/>
    <xs:complexType name="LocalisationRequestType">
        <xs:all>
            <xs:element name="UserID" type="xs:integer"/>
            <xs:element name="RadiusKM" type="xs:integer"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="LocalisationResponseType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="User" type="cp:UserType" xmlns:cp="http://ups/fr/carpooling/schemas"/>
        </xs:sequence>
        <xs:attribute name="UserID" type="xs:integer"/>
        <xs:attribute name="RadiusKM" type="xs:integer"/>
    </xs:complexType>
    <xs:complexType name="UserType">
        <xs:sequence>
            <xs:element name="LastName" type="xs:string"/>
            <xs:element name="FirstName" type="xs:string"/>
            <xs:element name="UPSMail" type="cp:MailType" xmlns:cp="http://ups/fr/carpooling/schemas"/>
            <xs:element name="Address" type="xs:string"/>
            <xs:element name="ZipCode" type="xs:integer"/>
            <xs:element name="Town" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="MailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== dam4256/ups-carpooling/Carpooling-Spring-WS/src/main/resources/localisation/LocalisationResponse.xml
<LocalisationResponse xmlns="http://ups/fr/carpooling/schemas"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
        xs:schemaLocation="http://ups/fr/carpooling/schemas Localisation.xsd "
        UserID="1"
        RadiusKM="5">
    <User>
        <LastName>Silvestre</LastName>
        <FirstName>Franck</FirstName>
        <UPSMail>franck.silvestre@univ-tlse3.fr</UPSMail>
        <Address>118 route de Narbonne</Address>
        <ZipCode>31520</ZipCode>
        <Town>Toulouse</Town>
    </User>
    <User>
        <LastName>Massie</LastName>
        <FirstName>Henry</FirstName>
        <UPSMail>henry.massie@univ-tlse3.fr</UPSMail>
        <Address>rue sylvain dauriac</Address>
        <ZipCode>31506</ZipCode>
        <Town>Toulouse</Town>
    </User>
    <User>
        <LastName>Cherbonneau</LastName>
        <FirstName>Bernard</FirstName>
        <UPSMail>bernard.cherbonneau@univ-tlse3.fr</UPSMail>
        <Address>rue d'alger</Address>
        <ZipCode>31500</ZipCode>
        <Town>Toulouse</Town>
    </User>
</LocalisationResponse>

=== dam4256/ups-carpooling/Carpooling-Spring-WS/src/main/resources/LocalisationResponse.xml
<LocalisationResponse xmlns="http://ups/fr/carpooling/schemas"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
        xs:schemaLocation="http://ups/fr/carpooling/schemas Localisation.xsd "
        UserID="1"
        RadiusKM="5">
    <User>
        <LastName>SYLVESTRE</LastName>
        <FirstName>Franck</FirstName>
        <UPSMail>sylvestre.franck@univ-tlse3.fr</UPSMail>
        <Address>118 route de Narbonne</Address>
        <ZipCode>31520</ZipCode>
        <Town>Toulouse</Town>
    </User>
    <User>
        <LastName>MASSIE</LastName>
        <FirstName>Henry</FirstName>
        <UPSMail>massie.henry@univ-tlse3.fr</UPSMail>
        <Address>rue rue sylvain dauriac</Address>
        <ZipCode>31506</ZipCode>
        <Town>Toulouse</Town>
    </User>
    <User>
        <LastName>CHERBONNAUD</LastName>
        <FirstName>Bernard</FirstName>
        <UPSMail>cherbonneau.bernard@univ-tlse3.fr</UPSMail>
        <Address>rue d'alger</Address>
        <ZipCode>31500</ZipCode>
        <Town>Toulouse</Town>
    </User>
</LocalisationResponse>
